"""Created job skill table

Revision ID: 77da76f386b7
Revises: 4689ac47df97
Create Date: 2020-07-24 06:42:20.996180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77da76f386b7'
down_revision = '4689ac47df97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_skill',
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_skills')
    # ### end Alembic commands ###
