"""Created work experience skill table

Revision ID: 4689ac47df97
Revises: d9d6d81bc90f
Create Date: 2020-07-24 06:42:06.394111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4689ac47df97'
down_revision = 'd9d6d81bc90f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_experience_skill',
    sa.Column('work_experience_id', sa.Integer(), nullable=True),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], ),
    sa.ForeignKeyConstraint(['work_experience_id'], ['work_experience.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_experience_skills')
    # ### end Alembic commands ###
