"""Created related skills table

Revision ID: c4b60a7cb56f
Revises: 7424d644a7aa
Create Date: 2020-07-24 06:41:05.585681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4b60a7cb56f'
down_revision = '7424d644a7aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('related_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.Column('related_skill_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['related_skill_id'], ['skill.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('related_skills')
    # ### end Alembic commands ###
