"""Added related skills

Revision ID: 5a53df60f031
Revises: 3ebedd1c0c83
Create Date: 2020-07-20 21:46:41.195263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a53df60f031'
down_revision = '3ebedd1c0c83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('related_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.Column('related_skill_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['related_skill_id'], ['skill.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('related_skills')
    # ### end Alembic commands ###
