"""Added columns

Revision ID: 651f05d33302
Revises: ef025f74b2c5
Create Date: 2020-07-20 15:18:39.760003

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '651f05d33302'
down_revision = 'ef025f74b2c5'
branch_labels = None
depends_on = None

gender_enum = postgresql.ENUM('male', 'female', 'other', name='enum_gender')
role_enum = postgresql.ENUM('candidate', 'employer', name='enum_role')


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    gender_enum.create(op.get_bind())
    role_enum.create(op.get_bind())

    op.add_column('user', sa.Column('email', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('first_name', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('gender', gender_enum, nullable=True))
    op.add_column('user', sa.Column('last_name', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('role', role_enum, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'gender')
    op.drop_column('user', 'first_name')
    op.drop_column('user', 'email')

    gender_enum.drop(op.get_bind())
    role_enum.drop(op.get_bind())

    # ### end Alembic commands ###
